# Generated by Django 4.2.26 on 2025-12-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_farmerprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='officerprofile',
            name='name',
            field=models.CharField(default='Unknown Officer', max_length=255),
            preserve_default=False,
        ),
    ]
