# Generated by Django 4.2.26 on 2026-01-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_officerprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
