# Generated by Django 4.2.26 on 2025-12-24 09:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventnotification',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='eventnotification',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventnotification',
            name='farmer',
        ),
        migrations.AlterModelOptions(
            name='eventattendance',
            options={'ordering': ['-registered_at'], 'verbose_name': 'Event Attendance', 'verbose_name_plural': 'Event Attendances'},
        ),
        migrations.RenameField(
            model_name='eventattendance',
            old_name='created_at',
            new_name='registered_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='officer',
        ),
        migrations.RemoveField(
            model_name='eventattendance',
            name='responded_at',
        ),
        migrations.RemoveField(
            model_name='eventattendance',
            name='response',
        ),
        migrations.AddField(
            model_name='event',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AddField(
            model_name='event',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='status',
            field=models.CharField(choices=[('interested', 'Interested'), ('attending', 'Attending'), ('attended', 'Attended'), ('not_attending', 'Not Attending')], default='interested', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventattendance',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['-event_date'], name='events_even_event_d_b32ef4_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_by'], name='events_even_created_95418c_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_active'], name='events_even_is_acti_82811f_idx'),
        ),
        migrations.DeleteModel(
            name='EventNotification',
        ),
    ]
