# Generated by Django 4.2.26 on 2025-12-29 05:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Main heading (e.g., 'Rubber Market Price')", max_length=200)),
                ('value', models.CharField(help_text="Primary value/metric (e.g., 'RSS-1: LKR 885.00')", max_length=100)),
                ('subtitle', models.CharField(help_text="Supporting text (e.g., '+2.5% from yesterday')", max_length=200)),
                ('image', models.ImageField(help_text='Background image for carousel card (recommended: 1200x600px)', upload_to='carousel/%Y/%m/')),
                ('color', models.CharField(default='#1B5E20', help_text='Hex color code for card background', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #1B5E20)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')])),
                ('icon', models.CharField(default='trending-up', help_text='Ionicon name (e.g., trending-up, water-outline, warning-outline)', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is visible in the carousel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, help_text='Admin user who created this item', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Carousel Item',
                'verbose_name_plural': 'Carousel Items',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['order', 'is_active'], name='carousel_ca_order_23ffe8_idx'), models.Index(fields=['created_at'], name='carousel_ca_created_cc3402_idx')],
            },
        ),
    ]
