[build]
builder = "NIXPACKS"

[deploy]
startCommand = "daphne -b 0.0.0.0 -p $PORT rubber_farm_api.asgi:application"
healthcheckPath = "/api/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
