# Generated by Django 4.2.26 on 2026-01-07 06:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_buyerprofile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatexQualityReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ph_value', models.FloatField(help_text='pH level (0-14)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)])),
                ('turbidity_ntu', models.FloatField(help_text='Turbidity in NTU (Nephelometric Turbidity Units)', validators=[django.core.validators.MinValueValidator(0)])),
                ('drc_percent', models.FloatField(help_text='Dry Rubber Content (%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('temperature_celsius', models.FloatField(blank=True, help_text='Ambient temperature in Celsius', null=True)),
                ('humidity_percent', models.FloatField(blank=True, help_text='Relative humidity (%)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('rss_grade', models.CharField(choices=[('RSS1', 'RSS1 - Premium Grade'), ('RSS2', 'RSS2 - High Quality'), ('RSS3', 'RSS3 - Standard Quality'), ('RSS4', 'RSS4 - Low Quality'), ('REJECTED', 'Rejected - Poor Quality')], db_index=True, editable=False, max_length=20)),
                ('quality_status', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], editable=False, max_length=20)),
                ('quality_score', models.IntegerField(editable=False, help_text='Overall quality score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('estimated_price_per_kg', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Estimated price in LKR per kg based on grade', max_digits=10, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, help_text='Additional notes from farmer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latex_readings', to='users.farmerprofile')),
            ],
            options={
                'verbose_name': 'Latex Quality Reading',
                'verbose_name_plural': 'Latex Quality Readings',
                'db_table': 'latex_quality_readings',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LatexQualityAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('LOW_QUALITY', 'Low Quality Detected'), ('HIGH_TURBIDITY', 'High Turbidity'), ('ABNORMAL_PH', 'Abnormal pH Level'), ('LOW_DRC', 'Low Dry Rubber Content'), ('SPOILAGE_RISK', 'Spoilage Risk')], max_length=30)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, max_length=10)),
                ('message', models.TextField(help_text='Alert message for farmer')),
                ('recommendations', models.TextField(blank=True, help_text='Actionable recommendations to fix the issue')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_alerts', to='users.farmerprofile')),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='latex_quality.latexqualityreading')),
            ],
            options={
                'verbose_name': 'Latex Quality Alert',
                'verbose_name_plural': 'Latex Quality Alerts',
                'db_table': 'latex_quality_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='latexqualityreading',
            index=models.Index(fields=['farmer', '-timestamp'], name='latex_quali_farmer__6a1282_idx'),
        ),
        migrations.AddIndex(
            model_name='latexqualityreading',
            index=models.Index(fields=['rss_grade'], name='latex_quali_rss_gra_de5cf9_idx'),
        ),
        migrations.AddIndex(
            model_name='latexqualityreading',
            index=models.Index(fields=['quality_status'], name='latex_quali_quality_806561_idx'),
        ),
        migrations.AddIndex(
            model_name='latexqualityalert',
            index=models.Index(fields=['farmer', '-created_at'], name='latex_quali_farmer__ae3ff4_idx'),
        ),
        migrations.AddIndex(
            model_name='latexqualityalert',
            index=models.Index(fields=['severity', 'is_read'], name='latex_quali_severit_bd61fd_idx'),
        ),
    ]
