# Generated by Django 4.2.26 on 2025-12-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('week_high', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('week_low', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('month_high', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('month_low', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_volume', models.CharField(default='N/A', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Market Statistic',
                'verbose_name_plural': 'Market Statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ScrapingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('grades_scraped', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RubberPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='LKR', max_length=10)),
                ('auction_date', models.DateField()),
                ('change_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-auction_date', 'grade'],
                'indexes': [models.Index(fields=['-auction_date'], name='api_rubberp_auction_a1bcf2_idx'), models.Index(fields=['grade'], name='api_rubberp_grade_0e0693_idx')],
                'unique_together': {('grade', 'auction_date')},
            },
        ),
    ]
