# Generated by Django 4.2.26 on 2025-12-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseDetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('disease_detected', models.CharField(max_length=100)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image_size', models.CharField(blank=True, max_length=50)),
                ('processing_time_ms', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Disease Detection Log',
                'verbose_name_plural': 'Disease Detection Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
