# Generated by Django 4.2.26 on 2025-12-31 06:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RubberPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('rss3', 'RSS3'), ('tsr20', 'TSR20'), ('latex', 'Latex 60%'), ('crepe', 'Crepe'), ('custom', 'Custom Grade')], max_length=20)),
                ('custom_grade_name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in LKR per kilogram', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_rubber_prices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rubber Price',
                'verbose_name_plural': 'Rubber Prices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_changes', to=settings.AUTH_USER_MODEL)),
                ('rubber_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='buyerprices.rubberprice')),
            ],
            options={
                'verbose_name': 'Price History',
                'verbose_name_plural': 'Price Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('rss3', 'RSS3'), ('tsr20', 'TSR20'), ('latex', 'Latex 60%'), ('crepe', 'Crepe'), ('custom', 'Custom Grade')], max_length=20)),
                ('target_price', models.DecimalField(decimal_places=2, help_text='Alert when price reaches this amount', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubber_price_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Price Alert',
                'verbose_name_plural': 'Price Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='rubberprice',
            index=models.Index(fields=['buyer', 'is_active'], name='buyerprices_buyer_i_4ebbf4_idx'),
        ),
        migrations.AddIndex(
            model_name='rubberprice',
            index=models.Index(fields=['effective_date', 'is_active'], name='buyerprices_effecti_317955_idx'),
        ),
        migrations.AddIndex(
            model_name='rubberprice',
            index=models.Index(fields=['grade', 'is_active'], name='buyerprices_grade_95999f_idx'),
        ),
    ]
