# Generated by Django 4.2.26 on 2025-12-31 08:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buyerprices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('rss1', 'RSS1'), ('rss2', 'RSS2'), ('rss3', 'RSS3'), ('rss4', 'RSS4'), ('rss5', 'RSS5'), ('latex', 'Latex 60%'), ('tsr20', 'TSR20'), ('crepe', 'Crepe'), ('custom', 'Custom Grade')], db_index=True, max_length=50)),
                ('custom_grade_name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in LKR per kilogram', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, max_length=1000, null=True)),
                ('effective_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(limit_choices_to={'role': 'buyer'}, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_prices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Buyer Price',
                'verbose_name_plural': 'Buyer Prices',
                'db_table': 'buyer_prices',
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='rubberprice',
            name='buyer',
        ),
        migrations.AddField(
            model_name='pricealert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pricealert',
            name='farmer',
            field=models.ForeignKey(limit_choices_to={'role': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pricealert',
            name='grade',
            field=models.CharField(choices=[('rss1', 'RSS1'), ('rss2', 'RSS2'), ('rss3', 'RSS3'), ('rss4', 'RSS4'), ('rss5', 'RSS5'), ('latex', 'Latex 60%'), ('tsr20', 'TSR20'), ('crepe', 'Crepe'), ('custom', 'Custom Grade')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pricealert',
            name='target_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterUniqueTogether(
            name='pricealert',
            unique_together={('farmer', 'grade', 'is_active')},
        ),
        migrations.AlterModelTable(
            name='pricealert',
            table='price_alerts',
        ),
        migrations.DeleteModel(
            name='PriceHistory',
        ),
        migrations.DeleteModel(
            name='RubberPrice',
        ),
        migrations.AddIndex(
            model_name='buyerprice',
            index=models.Index(fields=['buyer', 'effective_date', 'is_active'], name='buyer_price_buyer_i_e1ed60_idx'),
        ),
        migrations.AddIndex(
            model_name='buyerprice',
            index=models.Index(fields=['grade', 'effective_date'], name='buyer_price_grade_60e20c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='buyerprice',
            unique_together={('buyer', 'grade', 'custom_grade_name', 'effective_date', 'is_active')},
        ),
    ]
