# Generated by Django 5.2.7 on 2026-01-01 09:05

import buyerprices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyerprices', '0003_buyerprice_effective_period'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyerprice',
            options={'ordering': ['-effective_from', '-created_at'], 'verbose_name': 'Buyer Price', 'verbose_name_plural': 'Buyer Prices'},
        ),
        migrations.RemoveIndex(
            model_name='buyerprice',
            name='buyer_price_buyer_i_e1ed60_idx',
        ),
        migrations.RemoveIndex(
            model_name='buyerprice',
            name='buyer_price_grade_60e20c_idx',
        ),
        migrations.RenameIndex(
            model_name='buyerprice',
            new_name='buyer_price_buyer_i_844335_idx',
            old_fields=('buyer', 'effective_from', 'is_active'),
        ),
        migrations.RenameIndex(
            model_name='buyerprice',
            new_name='buyer_price_grade_38a805_idx',
            old_fields=('grade', 'effective_from'),
        ),
        migrations.AlterField(
            model_name='buyerprice',
            name='effective_to',
            field=models.DateTimeField(db_index=True, default=buyerprices.models.default_effective_to),
        ),
    ]
